// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nemo/incentive/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryRewardsRequest is the request type for the Query/Rewards RPC method.
type QueryRewardsRequest struct {
	// owner is the address of the user to query rewards for.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// reward_type is the type of reward to query rewards for, e.g. hard, earn,
	// swap.
	RewardType string `protobuf:"bytes,2,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"`
	// unsynchronized is a flag to query rewards that are not simulated for reward
	// synchronized for the current block.
	Unsynchronized bool `protobuf:"varint,3,opt,name=unsynchronized,proto3" json:"unsynchronized,omitempty"`
}

func (m *QueryRewardsRequest) Reset()         { *m = QueryRewardsRequest{} }
func (m *QueryRewardsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRewardsRequest) ProtoMessage()    {}
func (*QueryRewardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{2}
}
func (m *QueryRewardsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardsRequest.Merge(m, src)
}
func (m *QueryRewardsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardsRequest proto.InternalMessageInfo

func (m *QueryRewardsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryRewardsRequest) GetRewardType() string {
	if m != nil {
		return m.RewardType
	}
	return ""
}

func (m *QueryRewardsRequest) GetUnsynchronized() bool {
	if m != nil {
		return m.Unsynchronized
	}
	return false
}

// QueryRewardsResponse is the response type for the Query/Rewards RPC method.
type QueryRewardsResponse struct {
	USDXMintingClaims           USDXMintingClaims           `protobuf:"bytes,1,rep,name=usdx_minting_claims,json=usdxMintingClaims,proto3,castrepeated=USDXMintingClaims" json:"usdx_minting_claims"`
	HardLiquidityProviderClaims HardLiquidityProviderClaims `protobuf:"bytes,2,rep,name=hard_liquidity_provider_claims,json=hardLiquidityProviderClaims,proto3,castrepeated=HardLiquidityProviderClaims" json:"hard_liquidity_provider_claims"`
	DelegatorClaims             DelegatorClaims             `protobuf:"bytes,3,rep,name=delegator_claims,json=delegatorClaims,proto3,castrepeated=DelegatorClaims" json:"delegator_claims"`
	SwapClaims                  SwapClaims                  `protobuf:"bytes,4,rep,name=swap_claims,json=swapClaims,proto3,castrepeated=SwapClaims" json:"swap_claims"`
	SavingsClaims               SavingsClaims               `protobuf:"bytes,5,rep,name=savings_claims,json=savingsClaims,proto3,castrepeated=SavingsClaims" json:"savings_claims"`
	EarnClaims                  EarnClaims                  `protobuf:"bytes,6,rep,name=earn_claims,json=earnClaims,proto3,castrepeated=EarnClaims" json:"earn_claims"`
}

func (m *QueryRewardsResponse) Reset()         { *m = QueryRewardsResponse{} }
func (m *QueryRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRewardsResponse) ProtoMessage()    {}
func (*QueryRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{3}
}
func (m *QueryRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardsResponse.Merge(m, src)
}
func (m *QueryRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardsResponse proto.InternalMessageInfo

func (m *QueryRewardsResponse) GetUSDXMintingClaims() USDXMintingClaims {
	if m != nil {
		return m.USDXMintingClaims
	}
	return nil
}

func (m *QueryRewardsResponse) GetHardLiquidityProviderClaims() HardLiquidityProviderClaims {
	if m != nil {
		return m.HardLiquidityProviderClaims
	}
	return nil
}

func (m *QueryRewardsResponse) GetDelegatorClaims() DelegatorClaims {
	if m != nil {
		return m.DelegatorClaims
	}
	return nil
}

func (m *QueryRewardsResponse) GetSwapClaims() SwapClaims {
	if m != nil {
		return m.SwapClaims
	}
	return nil
}

func (m *QueryRewardsResponse) GetSavingsClaims() SavingsClaims {
	if m != nil {
		return m.SavingsClaims
	}
	return nil
}

func (m *QueryRewardsResponse) GetEarnClaims() EarnClaims {
	if m != nil {
		return m.EarnClaims
	}
	return nil
}

// QueryRewardFactorsRequest is the request type for the Query/RewardFactors RPC method.
type QueryRewardFactorsRequest struct {
}

func (m *QueryRewardFactorsRequest) Reset()         { *m = QueryRewardFactorsRequest{} }
func (m *QueryRewardFactorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRewardFactorsRequest) ProtoMessage()    {}
func (*QueryRewardFactorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{4}
}
func (m *QueryRewardFactorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardFactorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardFactorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardFactorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardFactorsRequest.Merge(m, src)
}
func (m *QueryRewardFactorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardFactorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardFactorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardFactorsRequest proto.InternalMessageInfo

// QueryRewardFactorsResponse is the response type for the Query/RewardFactors RPC method.
type QueryRewardFactorsResponse struct {
	UsdxMintingRewardFactors RewardIndexes      `protobuf:"bytes,1,rep,name=usdx_minting_reward_factors,json=usdxMintingRewardFactors,proto3,castrepeated=RewardIndexes" json:"usdx_minting_reward_factors"`
	HardSupplyRewardFactors  MultiRewardIndexes `protobuf:"bytes,2,rep,name=hard_supply_reward_factors,json=hardSupplyRewardFactors,proto3,castrepeated=MultiRewardIndexes" json:"hard_supply_reward_factors"`
	HardBorrowRewardFactors  MultiRewardIndexes `protobuf:"bytes,3,rep,name=hard_borrow_reward_factors,json=hardBorrowRewardFactors,proto3,castrepeated=MultiRewardIndexes" json:"hard_borrow_reward_factors"`
	DelegatorRewardFactors   MultiRewardIndexes `protobuf:"bytes,4,rep,name=delegator_reward_factors,json=delegatorRewardFactors,proto3,castrepeated=MultiRewardIndexes" json:"delegator_reward_factors"`
	SwapRewardFactors        MultiRewardIndexes `protobuf:"bytes,5,rep,name=swap_reward_factors,json=swapRewardFactors,proto3,castrepeated=MultiRewardIndexes" json:"swap_reward_factors"`
	SavingsRewardFactors     MultiRewardIndexes `protobuf:"bytes,6,rep,name=savings_reward_factors,json=savingsRewardFactors,proto3,castrepeated=MultiRewardIndexes" json:"savings_reward_factors"`
	EarnRewardFactors        MultiRewardIndexes `protobuf:"bytes,7,rep,name=earn_reward_factors,json=earnRewardFactors,proto3,castrepeated=MultiRewardIndexes" json:"earn_reward_factors"`
}

func (m *QueryRewardFactorsResponse) Reset()         { *m = QueryRewardFactorsResponse{} }
func (m *QueryRewardFactorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRewardFactorsResponse) ProtoMessage()    {}
func (*QueryRewardFactorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{5}
}
func (m *QueryRewardFactorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRewardFactorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRewardFactorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRewardFactorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRewardFactorsResponse.Merge(m, src)
}
func (m *QueryRewardFactorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRewardFactorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRewardFactorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRewardFactorsResponse proto.InternalMessageInfo

func (m *QueryRewardFactorsResponse) GetUsdxMintingRewardFactors() RewardIndexes {
	if m != nil {
		return m.UsdxMintingRewardFactors
	}
	return nil
}

func (m *QueryRewardFactorsResponse) GetHardSupplyRewardFactors() MultiRewardIndexes {
	if m != nil {
		return m.HardSupplyRewardFactors
	}
	return nil
}

func (m *QueryRewardFactorsResponse) GetHardBorrowRewardFactors() MultiRewardIndexes {
	if m != nil {
		return m.HardBorrowRewardFactors
	}
	return nil
}

func (m *QueryRewardFactorsResponse) GetDelegatorRewardFactors() MultiRewardIndexes {
	if m != nil {
		return m.DelegatorRewardFactors
	}
	return nil
}

func (m *QueryRewardFactorsResponse) GetSwapRewardFactors() MultiRewardIndexes {
	if m != nil {
		return m.SwapRewardFactors
	}
	return nil
}

func (m *QueryRewardFactorsResponse) GetSavingsRewardFactors() MultiRewardIndexes {
	if m != nil {
		return m.SavingsRewardFactors
	}
	return nil
}

func (m *QueryRewardFactorsResponse) GetEarnRewardFactors() MultiRewardIndexes {
	if m != nil {
		return m.EarnRewardFactors
	}
	return nil
}

// QueryApysRequest is the request type for the Query/Apys RPC method.
type QueryApyRequest struct {
}

func (m *QueryApyRequest) Reset()         { *m = QueryApyRequest{} }
func (m *QueryApyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryApyRequest) ProtoMessage()    {}
func (*QueryApyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{6}
}
func (m *QueryApyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryApyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryApyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryApyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryApyRequest.Merge(m, src)
}
func (m *QueryApyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryApyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryApyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryApyRequest proto.InternalMessageInfo

// QueryApysResponse is the response type for the Query/Apys RPC method.
type QueryApyResponse struct {
	Earn []Apy `protobuf:"bytes,1,rep,name=earn,proto3" json:"earn"`
}

func (m *QueryApyResponse) Reset()         { *m = QueryApyResponse{} }
func (m *QueryApyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryApyResponse) ProtoMessage()    {}
func (*QueryApyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d2d9f2a9aa72223, []int{7}
}
func (m *QueryApyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryApyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryApyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryApyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryApyResponse.Merge(m, src)
}
func (m *QueryApyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryApyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryApyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryApyResponse proto.InternalMessageInfo

func (m *QueryApyResponse) GetEarn() []Apy {
	if m != nil {
		return m.Earn
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "nemo.incentive.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "nemo.incentive.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryRewardsRequest)(nil), "nemo.incentive.v1beta1.QueryRewardsRequest")
	proto.RegisterType((*QueryRewardsResponse)(nil), "nemo.incentive.v1beta1.QueryRewardsResponse")
	proto.RegisterType((*QueryRewardFactorsRequest)(nil), "nemo.incentive.v1beta1.QueryRewardFactorsRequest")
	proto.RegisterType((*QueryRewardFactorsResponse)(nil), "nemo.incentive.v1beta1.QueryRewardFactorsResponse")
	proto.RegisterType((*QueryApyRequest)(nil), "nemo.incentive.v1beta1.QueryApyRequest")
	proto.RegisterType((*QueryApyResponse)(nil), "nemo.incentive.v1beta1.QueryApyResponse")
}

func init() {
	proto.RegisterFile("nemo/incentive/v1beta1/query.proto", fileDescriptor_6d2d9f2a9aa72223)
}

var fileDescriptor_6d2d9f2a9aa72223 = []byte{
	// 909 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0xb3, 0xf1, 0x8f, 0xc0, 0x8b, 0xd2, 0x34, 0x13, 0x93, 0x9a, 0x35, 0xac, 0x5d, 0x07,
	0xa5, 0x16, 0x3f, 0x6c, 0xc5, 0x88, 0x1b, 0x97, 0x84, 0x82, 0xa8, 0xa0, 0x52, 0xd9, 0x00, 0x42,
	0x5c, 0xa2, 0xb1, 0x77, 0x70, 0x16, 0x9c, 0x99, 0xcd, 0xcc, 0x6c, 0x9c, 0xad, 0x04, 0x12, 0x5c,
	0x80, 0x03, 0x12, 0x12, 0x57, 0xce, 0x1c, 0xfa, 0x57, 0x70, 0xac, 0xc4, 0xa5, 0x12, 0x17, 0x4e,
	0x2d, 0x4a, 0xf8, 0x43, 0xd0, 0xce, 0xcc, 0xae, 0xbd, 0xdb, 0xac, 0x9b, 0x4a, 0xbe, 0xad, 0xdf,
	0x7c, 0xdf, 0xfb, 0x7e, 0xde, 0xea, 0x3d, 0xcf, 0x42, 0x9b, 0x92, 0x63, 0xd6, 0xf3, 0xe9, 0x90,
	0x50, 0xe9, 0x9f, 0x92, 0xde, 0xe9, 0xee, 0x80, 0x48, 0xbc, 0xdb, 0x3b, 0x09, 0x09, 0x8f, 0xba,
	0x01, 0x67, 0x92, 0xa1, 0xad, 0x58, 0xd3, 0x4d, 0x35, 0x5d, 0xa3, 0xb1, 0x6b, 0x23, 0x36, 0x62,
	0x4a, 0xd2, 0x8b, 0x9f, 0xb4, 0xda, 0x7e, 0x65, 0xc4, 0xd8, 0x68, 0x4c, 0x7a, 0x38, 0xf0, 0x7b,
	0x98, 0x52, 0x26, 0xb1, 0xf4, 0x19, 0x15, 0xe6, 0xb4, 0x55, 0xe0, 0x87, 0x03, 0xe3, 0x66, 0x6f,
	0x17, 0x28, 0x86, 0x63, 0xec, 0x1f, 0x8b, 0x67, 0x88, 0x02, 0xcc, 0x71, 0x22, 0x6a, 0xd7, 0x00,
	0x7d, 0x12, 0xb7, 0x71, 0x4f, 0x05, 0x5d, 0x72, 0x12, 0x12, 0x21, 0xdb, 0x07, 0xb0, 0x99, 0x89,
	0x8a, 0x80, 0x51, 0x41, 0xd0, 0xbb, 0x50, 0xd5, 0xc9, 0x75, 0xab, 0x65, 0x75, 0x56, 0xfb, 0x4e,
	0xf7, 0xf2, 0xae, 0xbb, 0x3a, 0x6f, 0xbf, 0xfc, 0xf0, 0x71, 0x73, 0xc9, 0x35, 0x39, 0x6d, 0x69,
	0x8a, 0xba, 0x64, 0x82, 0xb9, 0x97, 0x78, 0xa1, 0x1a, 0x54, 0xd8, 0x84, 0x12, 0xae, 0x6a, 0xbe,
	0xe8, 0xea, 0x1f, 0xa8, 0x09, 0xab, 0x5c, 0xe9, 0x0e, 0x65, 0x14, 0x90, 0xfa, 0xb2, 0x3a, 0x03,
	0x1d, 0xfa, 0x34, 0x0a, 0x08, 0xda, 0x81, 0x6b, 0x21, 0x15, 0x11, 0x1d, 0x1e, 0x71, 0x46, 0xfd,
	0xfb, 0xc4, 0xab, 0x97, 0x5a, 0x56, 0xe7, 0x05, 0x37, 0x17, 0x6d, 0xff, 0x59, 0x81, 0x5a, 0xd6,
	0xd6, 0x34, 0xf3, 0x93, 0x05, 0x9b, 0xa1, 0xf0, 0xce, 0x0e, 0x8f, 0x7d, 0x2a, 0x7d, 0x3a, 0x3a,
	0xd4, 0x2f, 0xaf, 0x6e, 0xb5, 0x4a, 0x9d, 0xd5, 0x7e, 0xa7, 0xa8, 0xb5, 0xcf, 0x0e, 0x6e, 0x7f,
	0x71, 0x57, 0x67, 0xbc, 0x17, 0x27, 0xec, 0x77, 0xe3, 0x26, 0xcf, 0x1f, 0x37, 0x37, 0xf2, 0x27,
	0xe2, 0xc1, 0x93, 0x4b, 0x82, 0xee, 0x46, 0x6c, 0x9a, 0x09, 0xa1, 0xdf, 0x2d, 0x70, 0x8e, 0xe2,
	0x5e, 0xc7, 0xfe, 0x49, 0xe8, 0x7b, 0xbe, 0x8c, 0x0e, 0x03, 0xce, 0x4e, 0x7d, 0x8f, 0xf0, 0x84,
	0x6a, 0x59, 0x51, 0xf5, 0x8b, 0xa8, 0x3e, 0xc4, 0xdc, 0xfb, 0x38, 0x49, 0xbe, 0x67, 0x72, 0x35,
	0xdf, 0x76, 0xcc, 0xf7, 0xe0, 0x49, 0xb3, 0x51, 0xac, 0x11, 0x6e, 0xe3, 0xa8, 0xf8, 0x10, 0x7d,
	0x0d, 0xd7, 0x3d, 0x32, 0x26, 0x23, 0x2c, 0x59, 0xca, 0x53, 0x52, 0x3c, 0x3b, 0x45, 0x3c, 0xb7,
	0x13, 0xbd, 0x66, 0xb8, 0x61, 0x18, 0xd6, 0xb3, 0x71, 0xe1, 0xae, 0x7b, 0xd9, 0x00, 0xfa, 0x1c,
	0x56, 0xc5, 0x04, 0x07, 0x89, 0x4d, 0x59, 0xd9, 0xdc, 0x2c, 0xb2, 0x39, 0x98, 0xe0, 0x40, 0x3b,
	0x20, 0xe3, 0x00, 0x69, 0x48, 0xb8, 0x20, 0xd2, 0x67, 0x34, 0x80, 0x6b, 0x02, 0x9f, 0xfa, 0x74,
	0x24, 0x92, 0xd2, 0x15, 0x55, 0xfa, 0xb5, 0xc2, 0xd2, 0x5a, 0xad, 0xab, 0xbf, 0x64, 0xaa, 0xaf,
	0xcd, 0x46, 0x85, 0xbb, 0x26, 0x66, 0x7f, 0xc6, 0xec, 0x04, 0x73, 0x9a, 0x18, 0x54, 0xe7, 0xb3,
	0xbf, 0x8f, 0x39, 0xcd, 0xb1, 0xa7, 0x21, 0xe1, 0x02, 0x49, 0x9f, 0xdb, 0x0d, 0x78, 0x79, 0x66,
	0x82, 0x3f, 0xc0, 0x43, 0xc9, 0x78, 0xba, 0xaa, 0x3f, 0xae, 0x80, 0x7d, 0xd9, 0xa9, 0x99, 0xf2,
	0x08, 0x1a, 0x99, 0x21, 0x37, 0x4b, 0xf5, 0x95, 0x96, 0x99, 0x61, 0xdf, 0x2e, 0x62, 0xd4, 0x35,
	0xef, 0x50, 0x8f, 0x9c, 0x4d, 0xdf, 0xc1, 0x4c, 0x90, 0x08, 0xb7, 0x3e, 0x33, 0xce, 0x19, 0x04,
	0xf4, 0xbd, 0x05, 0xb6, 0x9a, 0x6a, 0x11, 0x06, 0xc1, 0x38, 0xca, 0x5b, 0x2f, 0xcf, 0xdf, 0xb3,
	0xbb, 0xe1, 0x58, 0xfa, 0xb3, 0xfe, 0xb6, 0xf1, 0x47, 0xf9, 0x13, 0x22, 0xdc, 0x1b, 0xb1, 0xcf,
	0x81, 0xb2, 0x29, 0x60, 0x18, 0x30, 0xce, 0xd9, 0x24, 0xcf, 0x50, 0x5a, 0x34, 0xc3, 0xbe, 0xb2,
	0xc9, 0x32, 0x7c, 0x07, 0xf5, 0xe9, 0xfa, 0xe4, 0x00, 0xca, 0x0b, 0x04, 0xd8, 0x4a, 0x5d, 0xb2,
	0xfe, 0x12, 0x36, 0xd5, 0x4a, 0xe5, 0xac, 0x2b, 0x0b, 0xb4, 0xde, 0x88, 0x0d, 0xb2, 0xae, 0xf7,
	0x61, 0x2b, 0x59, 0xb8, 0x9c, 0x71, 0x75, 0x81, 0xc6, 0x35, 0xe3, 0xf1, 0x54, 0xc7, 0x6a, 0x11,
	0x73, 0xc6, 0x2b, 0x8b, 0xec, 0x38, 0x36, 0xc8, 0xb8, 0xb6, 0x37, 0x60, 0x5d, 0x2d, 0xe2, 0x5e,
	0x10, 0x25, 0xcb, 0x79, 0x07, 0xae, 0x4f, 0x43, 0x66, 0x23, 0xdf, 0x81, 0x72, 0x9c, 0x6b, 0x56,
	0xaf, 0x51, 0x44, 0xb3, 0x17, 0x44, 0xe6, 0xfe, 0x54, 0xf2, 0xfe, 0x5f, 0x65, 0xa8, 0xa8, 0x5a,
	0xe8, 0x67, 0x0b, 0xaa, 0xfa, 0x82, 0x45, 0xaf, 0x17, 0x65, 0x3f, 0x7d, 0xa7, 0xdb, 0x6f, 0x5c,
	0x49, 0xab, 0x21, 0xdb, 0x3b, 0x3f, 0xfc, 0xfd, 0xdf, 0x6f, 0xcb, 0x2d, 0xe4, 0xf4, 0xe6, 0x7e,
	0x44, 0xa0, 0x5f, 0x2c, 0x58, 0x31, 0x17, 0x2b, 0x9a, 0x6f, 0x90, 0xbd, 0xf5, 0xed, 0x37, 0xaf,
	0x26, 0x36, 0x38, 0xb7, 0x14, 0xce, 0x4d, 0xd4, 0x2c, 0xc2, 0xe1, 0x86, 0xe1, 0x0f, 0x0b, 0xd6,
	0xb2, 0xb3, 0xb0, 0x7b, 0x05, 0xa3, 0xec, 0x5f, 0xaa, 0xdd, 0x7f, 0x9e, 0x14, 0x43, 0xd8, 0x55,
	0x84, 0x1d, 0xb4, 0x33, 0x9f, 0x30, 0x99, 0x45, 0xf4, 0x2d, 0x94, 0xf6, 0x82, 0x08, 0xdd, 0x9a,
	0x6b, 0x35, 0x9d, 0x24, 0xbb, 0xf3, 0x6c, 0xa1, 0x21, 0xd9, 0x56, 0x24, 0xaf, 0xa2, 0x46, 0xaf,
	0xf8, 0x33, 0x72, 0xff, 0xa3, 0x87, 0xe7, 0x8e, 0xf5, 0xe8, 0xdc, 0xb1, 0xfe, 0x3d, 0x77, 0xac,
	0x5f, 0x2f, 0x9c, 0xa5, 0x47, 0x17, 0xce, 0xd2, 0x3f, 0x17, 0xce, 0xd2, 0x97, 0xbb, 0x23, 0x5f,
	0x1e, 0x85, 0x83, 0xee, 0x90, 0x1d, 0xc7, 0xb9, 0xe1, 0x20, 0x14, 0x6f, 0x51, 0x22, 0x27, 0x8c,
	0x7f, 0xa3, 0x0b, 0x9e, 0xcd, 0x94, 0x8c, 0xbf, 0xcd, 0xc4, 0xa0, 0xaa, 0x3e, 0x25, 0xdf, 0xfe,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x36, 0x37, 0x61, 0x05, 0x28, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries module params.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Rewards queries reward information for a given user.
	Rewards(ctx context.Context, in *QueryRewardsRequest, opts ...grpc.CallOption) (*QueryRewardsResponse, error)
	// Rewards queries the reward factors.
	RewardFactors(ctx context.Context, in *QueryRewardFactorsRequest, opts ...grpc.CallOption) (*QueryRewardFactorsResponse, error)
	// Apy queries incentive reward apy for a reward.
	Apy(ctx context.Context, in *QueryApyRequest, opts ...grpc.CallOption) (*QueryApyResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/nemo.incentive.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Rewards(ctx context.Context, in *QueryRewardsRequest, opts ...grpc.CallOption) (*QueryRewardsResponse, error) {
	out := new(QueryRewardsResponse)
	err := c.cc.Invoke(ctx, "/nemo.incentive.v1beta1.Query/Rewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RewardFactors(ctx context.Context, in *QueryRewardFactorsRequest, opts ...grpc.CallOption) (*QueryRewardFactorsResponse, error) {
	out := new(QueryRewardFactorsResponse)
	err := c.cc.Invoke(ctx, "/nemo.incentive.v1beta1.Query/RewardFactors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Apy(ctx context.Context, in *QueryApyRequest, opts ...grpc.CallOption) (*QueryApyResponse, error) {
	out := new(QueryApyResponse)
	err := c.cc.Invoke(ctx, "/nemo.incentive.v1beta1.Query/Apy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries module params.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Rewards queries reward information for a given user.
	Rewards(context.Context, *QueryRewardsRequest) (*QueryRewardsResponse, error)
	// Rewards queries the reward factors.
	RewardFactors(context.Context, *QueryRewardFactorsRequest) (*QueryRewardFactorsResponse, error)
	// Apy queries incentive reward apy for a reward.
	Apy(context.Context, *QueryApyRequest) (*QueryApyResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Rewards(ctx context.Context, req *QueryRewardsRequest) (*QueryRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rewards not implemented")
}
func (*UnimplementedQueryServer) RewardFactors(ctx context.Context, req *QueryRewardFactorsRequest) (*QueryRewardFactorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardFactors not implemented")
}
func (*UnimplementedQueryServer) Apy(ctx context.Context, req *QueryApyRequest) (*QueryApyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apy not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nemo.incentive.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Rewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Rewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nemo.incentive.v1beta1.Query/Rewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Rewards(ctx, req.(*QueryRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RewardFactors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRewardFactorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RewardFactors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nemo.incentive.v1beta1.Query/RewardFactors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RewardFactors(ctx, req.(*QueryRewardFactorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Apy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryApyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Apy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nemo.incentive.v1beta1.Query/Apy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Apy(ctx, req.(*QueryApyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nemo.incentive.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Rewards",
			Handler:    _Query_Rewards_Handler,
		},
		{
			MethodName: "RewardFactors",
			Handler:    _Query_RewardFactors_Handler,
		},
		{
			MethodName: "Apy",
			Handler:    _Query_Apy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nemo/incentive/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRewardsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Unsynchronized {
		i--
		if m.Unsynchronized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.RewardType) > 0 {
		i -= len(m.RewardType)
		copy(dAtA[i:], m.RewardType)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RewardType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EarnClaims) > 0 {
		for iNdEx := len(m.EarnClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EarnClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.SavingsClaims) > 0 {
		for iNdEx := len(m.SavingsClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SavingsClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.SwapClaims) > 0 {
		for iNdEx := len(m.SwapClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SwapClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.DelegatorClaims) > 0 {
		for iNdEx := len(m.DelegatorClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegatorClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.HardLiquidityProviderClaims) > 0 {
		for iNdEx := len(m.HardLiquidityProviderClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HardLiquidityProviderClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.USDXMintingClaims) > 0 {
		for iNdEx := len(m.USDXMintingClaims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.USDXMintingClaims[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryRewardFactorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardFactorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardFactorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRewardFactorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRewardFactorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRewardFactorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EarnRewardFactors) > 0 {
		for iNdEx := len(m.EarnRewardFactors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EarnRewardFactors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.SavingsRewardFactors) > 0 {
		for iNdEx := len(m.SavingsRewardFactors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SavingsRewardFactors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.SwapRewardFactors) > 0 {
		for iNdEx := len(m.SwapRewardFactors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SwapRewardFactors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.DelegatorRewardFactors) > 0 {
		for iNdEx := len(m.DelegatorRewardFactors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegatorRewardFactors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.HardBorrowRewardFactors) > 0 {
		for iNdEx := len(m.HardBorrowRewardFactors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HardBorrowRewardFactors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.HardSupplyRewardFactors) > 0 {
		for iNdEx := len(m.HardSupplyRewardFactors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HardSupplyRewardFactors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.UsdxMintingRewardFactors) > 0 {
		for iNdEx := len(m.UsdxMintingRewardFactors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UsdxMintingRewardFactors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryApyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryApyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryApyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryApyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryApyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryApyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Earn) > 0 {
		for iNdEx := len(m.Earn) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Earn[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRewardsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.RewardType)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Unsynchronized {
		n += 2
	}
	return n
}

func (m *QueryRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.USDXMintingClaims) > 0 {
		for _, e := range m.USDXMintingClaims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.HardLiquidityProviderClaims) > 0 {
		for _, e := range m.HardLiquidityProviderClaims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.DelegatorClaims) > 0 {
		for _, e := range m.DelegatorClaims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.SwapClaims) > 0 {
		for _, e := range m.SwapClaims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.SavingsClaims) > 0 {
		for _, e := range m.SavingsClaims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.EarnClaims) > 0 {
		for _, e := range m.EarnClaims {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryRewardFactorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRewardFactorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.UsdxMintingRewardFactors) > 0 {
		for _, e := range m.UsdxMintingRewardFactors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.HardSupplyRewardFactors) > 0 {
		for _, e := range m.HardSupplyRewardFactors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.HardBorrowRewardFactors) > 0 {
		for _, e := range m.HardBorrowRewardFactors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.DelegatorRewardFactors) > 0 {
		for _, e := range m.DelegatorRewardFactors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.SwapRewardFactors) > 0 {
		for _, e := range m.SwapRewardFactors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.SavingsRewardFactors) > 0 {
		for _, e := range m.SavingsRewardFactors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.EarnRewardFactors) > 0 {
		for _, e := range m.EarnRewardFactors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryApyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryApyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Earn) > 0 {
		for _, e := range m.Earn {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unsynchronized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Unsynchronized = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field USDXMintingClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.USDXMintingClaims = append(m.USDXMintingClaims, USDXMintingClaim{})
			if err := m.USDXMintingClaims[len(m.USDXMintingClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardLiquidityProviderClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HardLiquidityProviderClaims = append(m.HardLiquidityProviderClaims, HardLiquidityProviderClaim{})
			if err := m.HardLiquidityProviderClaims[len(m.HardLiquidityProviderClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorClaims = append(m.DelegatorClaims, DelegatorClaim{})
			if err := m.DelegatorClaims[len(m.DelegatorClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapClaims = append(m.SwapClaims, SwapClaim{})
			if err := m.SwapClaims[len(m.SwapClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SavingsClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SavingsClaims = append(m.SavingsClaims, SavingsClaim{})
			if err := m.SavingsClaims[len(m.SavingsClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarnClaims", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarnClaims = append(m.EarnClaims, EarnClaim{})
			if err := m.EarnClaims[len(m.EarnClaims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardFactorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardFactorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardFactorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRewardFactorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRewardFactorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRewardFactorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsdxMintingRewardFactors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UsdxMintingRewardFactors = append(m.UsdxMintingRewardFactors, RewardIndex{})
			if err := m.UsdxMintingRewardFactors[len(m.UsdxMintingRewardFactors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardSupplyRewardFactors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HardSupplyRewardFactors = append(m.HardSupplyRewardFactors, MultiRewardIndex{})
			if err := m.HardSupplyRewardFactors[len(m.HardSupplyRewardFactors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HardBorrowRewardFactors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HardBorrowRewardFactors = append(m.HardBorrowRewardFactors, MultiRewardIndex{})
			if err := m.HardBorrowRewardFactors[len(m.HardBorrowRewardFactors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegatorRewardFactors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegatorRewardFactors = append(m.DelegatorRewardFactors, MultiRewardIndex{})
			if err := m.DelegatorRewardFactors[len(m.DelegatorRewardFactors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapRewardFactors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapRewardFactors = append(m.SwapRewardFactors, MultiRewardIndex{})
			if err := m.SwapRewardFactors[len(m.SwapRewardFactors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SavingsRewardFactors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SavingsRewardFactors = append(m.SavingsRewardFactors, MultiRewardIndex{})
			if err := m.SavingsRewardFactors[len(m.SavingsRewardFactors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarnRewardFactors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarnRewardFactors = append(m.EarnRewardFactors, MultiRewardIndex{})
			if err := m.EarnRewardFactors[len(m.EarnRewardFactors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryApyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryApyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryApyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryApyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryApyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryApyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Earn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Earn = append(m.Earn, Apy{})
			if err := m.Earn[len(m.Earn)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
