name: Continuous Integration (Default Checks)

on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: build application
        run: make build
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: run unit tests
        run: make test
      - name: run e2e tests
        run: make docker-build test-e2e
  validate-internal-testnet-genesis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
      - name: save version of fury that will be deployed if this pr is merged
        id: fury-version
        run: |
          echo "FURY_VERSION=$(cat ./ci/env/fury-internal-testnet/FURY.VERSION)" >> $GITHUB_OUTPUT
      - name: checkout repo from master
        uses: actions/checkout@v3
        with:
          ref: master
      - name: checkout version of fury that will be deployed if this pr is merged
        run: |
          git pull -p
          git checkout $FURY_VERSION
        env:
          FURY_VERSION: ${{ steps.fury-version.outputs.FURY_VERSION }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: build fury cli
        run: make install
      - name: checkout repo from current commit to validate current branch's genesis
        uses: actions/checkout@v3
      - name: validate testnet genesis
        run: fury validate-genesis ci/env/fury-internal-testnet/genesis.json
  validate-protonet-genesis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo from current commit
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
      - name: build fury cli
        run: make install
      - name: validate protonet genesis
        run: fury validate-genesis ci/env/fury-protonet/genesis.json
